### ISSUE TITLE
async/await support ?

### ISSUE THREAD

**Issue by advancedtw** [nsagora/peppermint#39]
is there any plan to support modern async with this library?  
btw good work with the declarative api ! clearly underrated package imho

**Comment by alexcristea** [comment]
Thank you for the feedback @advancedtw. 

The short answer is yes, async/await is in plan. 

I'm currently working on adopting the latest swift features. Async/await is part of the effort.

**Comment by advancedtw** [comment]
very glad to hear that and I'm looking forward to try it out

**Comment by alexcristea** [comment]
@advancedtw i've added basic support for `async/await` on the `AsyncConstraint`, which are inherited by default by all `Constraint` implementations.

However, I curious to find out more about your use cases and how you plan using `async/await` with this library? Thank you!

**Comment by alexcristea** [comment]
The support for `async/await` is released in [v1.2.0](https://github.com/nsagora/peppermint/releases/tag/1.2.0).
